output_model_dir: ../runs/split/GraphMVP/_test/esol/scaff/train_prop=0.8
input_model_file: ../weights/pretrained/GraphMVP_regression.pth
multiple_seeds:
- 1
- 2
train_prop: 0.8
split: scaffold
dataset: esol
epochs: 2
