output_model_dir: ../results/split/GraphMVP/_test/esol/scaff/train_prop=0.6
input_model_file: ../weights/pretrained/GraphMVP_regression.pth
multiple_seeds:
- 1
- 2
train_prop: 0.6
split: scaffold
dataset: esol
epochs: 2
