output_model_dir: ../runs/split/GraphMVP/freesolv/random/train_prop=0.8
input_model_file: ../weights/pretrained/GraphMVP_regression.pth
multiple_seeds:
- 4
- 5
- 6
train_prop: 0.8
split: random
dataset: freesolv
epochs: 1000
patience: 35
minimum_epochs: 120
