output_model_dir: ../runs/split/GraphCL/esol/random/train_prop=0.8
input_model_file: ../weights/pretrained/GraphCL_regression.pth
multiple_seeds:
- 1
- 2
- 3
train_prop: 0.8
split: random
dataset: esol
epochs: 1000
patience: 35
minimum_epochs: 120
