experiment_name: 3DInfomax_sider_static_noise=0.05
logdir: runs/static_noise/3DInfomax/sider/noise=0.05
multiple_seeds:
- 1
- 2
- 3
pretrain_checkpoint: runs/PNA_3DInfomax_drugs_smaller/best_checkpoint.pt
transfer_layers:
- gnn.
dataset: ogbg-molsider
noise_level: 0.05
dynamic_noise: False
num_epochs: 1000
batch_size: 32
log_iterations: 30
patience: 60
minimum_epochs: 120
loss_func: OGBNanLabelBCEWithLogitsLoss
required_data:
- dgl_graph
- targets
metrics:
- prcauc
- rocauc
optimizer: Adam
optimizer_params:
  lr: 0.001
scheduler_step_per_batch: False
lr_scheduler: WarmUpWrapper
lr_scheduler_params:
  warmup_steps: [700, 700, 350]
  interpolation: linear
  wrapped_scheduler: ReduceLROnPlateau
  factor: 0.5
  patience: 25
  min_lr: 1.0e-06
  mode: min
  verbose: True
model_type: PNA
model_parameters:
  target_dim: 27
  hidden_dim: 50
  mid_batch_norm: True
  last_batch_norm: True
  readout_batchnorm: True
  batch_norm_momentum: 0.1
  readout_hidden_dim: 50
  readout_layers: 2
  dropout: 0.0
  propagation_depth: 3
  aggregators:
  - mean
  - max
  - min
  - std
  scalers:
  - identity
  - amplification
  - attenuation
  readout_aggregators:
  - min
  - max
  - mean
  - sum
  pretrans_layers: 2
  posttrans_layers: 1
  residual: True
