output_model_dir: ../runs/split/GraphCL/clintox/scaff/train_prop=0.8
input_model_file: ../weights/pretrained/GraphCL_classification.pth
multiple_seeds:
- 1
- 2
- 3
train_prop: 0.8
split: scaffold
dataset: clintox
epochs: 1000
patience: 35
minimum_epochs: 120
