FROM nvidia/cuda:11.8.0-devel-ubuntu22.04

# Set environment variables
ENV DEBIAN_FRONTEND=noninteractive
ENV PATH="/opt/conda/bin:$PATH"

# Install system dependencies
COPY installed_packages_clean.txt /tmp/installed_packages_clean.txt
RUN apt-get update && \
    xargs -a /tmp/installed_packages_clean.txt apt-get install -y && \
    rm -rf /var/lib/apt/lists/* /tmp/installed_packages_clean.txt

# Install Miniconda
RUN wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O /miniconda.sh && \
    bash /miniconda.sh -b -p /opt/conda && \
    rm /miniconda.sh

# Create Conda environment
COPY environment_test.yml /tmp/environment_test.yml
RUN conda env create -f /tmp/environment_test.yml && \
    rm /tmp/environment_test.yml

# Activate Conda environment
SHELL ["/bin/bash", "-c"]
RUN echo "source activate 3DInfomax" > ~/.bashrc
ENV CONDA_DEFAULT_ENV=3DInfomax
ENV PATH="/opt/conda/envs/3DInfomax/bin:$PATH"

# Install additional Python dependencies
COPY requirements_test.txt /tmp/requirements_test.txt
RUN pip install --no-cache-dir -r /tmp/requirements_test.txt && \
    rm /tmp/requirements_test.txt

# Install PyG dependencies
RUN pip install torch-scatter torch-sparse -f https://data.pyg.org/whl/torch-2.4.0+cu118.html

# Set working directory
WORKDIR /workspace

CMD ["/bin/bash"]
