name: 3DInfomax
channels:
  - defaults
  - pyg
  - pytorch
  - dglteam
  - nvidia
  - conda-forge
dependencies:
  - python=3.9
  - pytorch-cuda=11.8
  - pytorch=2.4.0
  - torchvision
  - torchaudio
  - cudatoolkit=11.8
  - rdkit
  # - dgl-cuda11.8
  - pot
  - numpy
  - certifi
  - ogb
  - pip
  # - pip:
  #     - icecream
  #     - tensorboard
  #     - torch-geometric
  #     - torch-scatter 
  #     - torch-sparse 
  #     - torch-cluster 
  #     - torch-spline-conv 
