name: 3DInfomax
channels:
  - defaults
  - pyg
  - pytorch
  - dglteam
  - nvidia
  - conda-forge
dependencies:
  - python=3.9
  - pytorch-cuda=11.8
  - pytorch=2.4.0
  - torchvision=0.19.0
  - torchaudio=2.4.0
  - cudatoolkit=11.8
  - rdkit
  - pot
  - numpy
  - certifi
  - ogb=1.3.3
  - pip

