output_model_dir: ../runs/split/GraphCL/toxcast/random/train_prop=0.6
input_model_file: ../weights/pretrained/GraphCL_classification.pth
multiple_seeds:
- 4
- 5
- 6
train_prop: 0.6
split: random
dataset: toxcast
epochs: 1000
patience: 35
minimum_epochs: 120
