output_model_dir: ../runs/split/GraphMVP/muv/scaff/train_prop=0.8
input_model_file: ../weights/pretrained/GraphMVP_classification.pth
multiple_seeds:
- 1
- 2
- 3
train_prop: 0.8
split: scaffold
dataset: muv
epochs: 1000
patience: 35
minimum_epochs: 120
