output_model_dir: ../results/split/GraphMVP/_test/freesolv_random=0.7
input_model_file: ../weights/pretrained/GraphMVP_regression.pth
multiple_seeds:
- 1
- 2
train_prop: 0.7
split: random
dataset: freesolv
epochs: 2
