output_model_dir: ../runs/split/GraphCL/sider/scaff/train_prop=0.8
input_model_file: ../weights/pretrained/GraphCL_classification.pth
multiple_seeds:
- 4
- 5
- 6
train_prop: 0.8
split: scaffold
dataset: sider
epochs: 1000
patience: 35
minimum_epochs: 120
