batch_size: 500

checkpoint:

collate_function: NodeDropCollate

collate_params:
  drop_ratio: 0.2

config: runs/pre-train_graphCL_smaller_model/PNA_drugs_graphcl_140000_drugs_smaller_model_123_06-05_13-51-39/pre-train_GraphCL_GEOM-Drugs_smaller_model.yml

critic_loss: MSELoss

critic_loss_params: {}

critic_parameters:

critic_type:

dataset: drugs

device: cuda:0

dist_embedding: no

dynamic_noise: yes

eval_on_test: yes

eval_per_epochs: 0

exclude_from_transfer: []

expensive_log_iterations: 100

experiment_name: graphcl_140000_drugs_smaller_model

force_random_split: no

frozen_layers: []

linear_probing_samples: 500

log_iterations: 2

logdir: runs/pre-train_graphCL_smaller_model

loss_func: NTXent

loss_params:
  tau: 0.1

lr_scheduler: WarmUpWrapper

lr_scheduler_params:
  cooldown: 20
  factor: 0.6
  min_lr: 1.0e-06
  mode: min
  patience: 25
  threshold: 0.0001
  verbose: yes
  warmup_steps:
    - 700
  wrapped_scheduler: ReduceLROnPlateau

main_metric: loss

main_metric_goal: min

metrics:
  - positive_similarity
  - negative_similarity
  - contrastive_accuracy
  - true_negative_rate
  - true_positive_rate
  - uniformity
  - alignment
  - batch_variance
  - dimension_covariance

minimum_epochs: 0

model3d_parameters:

model3d_type:

model_parameters:
  aggregators:
    - mean
    - max
    - min
    - std
  batch_norm_momentum: 0.93
  dropout: 0.0
  hidden_dim: 50
  last_batch_norm: yes
  mid_batch_norm: yes
  posttrans_layers: 1
  pretrans_layers: 2
  propagation_depth: 3
  readout_aggregators:
    - min
    - max
    - mean
  readout_batchnorm: yes
  readout_hidden_dim: 50
  readout_layers: 2
  residual: yes
  scalers:
    - identity
    - amplification
    - attenuation
  target_dim: 256

model_type: PNA

models_to_save: []

multiple_seeds: []

noise_level: 0.0

num_conformers: 3

num_epochs: 1000

num_epochs_local_only: 1

num_radial: 6

num_train: 140000

num_val:

optimizer: Adam

optimizer_params:
  lr: 8.0e-05

patience: 35

pretrain_checkpoint:

required_data:
  - dgl_graph

reuse_pre_train_data: no

scheduler_step_per_batch: no

seed: 123

seed_data: 123

targets: []

tensorboard_functions: []

train_prop: 0.8

train_sampler:

trainer: graphcl_trainer

transfer_3d: no

transfer_layers: []

transferred_lr:

use_e_features: yes

val_per_batch: yes
