output_model_dir: ../runs/split/GraphMVP/_test/bace/scaff/train_prop=0.8
input_model_file: ../weights/pretrained/GraphMVP_classification.pth
multiple_seeds:
- 1
- 2
train_prop: 0.8
split: scaffold
dataset: bace
epochs: 2
