output_model_dir: ../runs/split/GraphMVP/lipo/random/train_prop=0.6
input_model_file: ../weights/pretrained/GraphMVP_regression.pth
multiple_seeds:
- 4
- 5
- 6
train_prop: 0.6
split: random
dataset: lipophilicity
epochs: 1000
patience: 35
minimum_epochs: 120
