output_model_dir: ../runs/split/GraphCL/bbbp/scaff/train_prop=0.7
input_model_file: ../weights/pretrained/GraphCL_classification.pth
multiple_seeds:
- 4
- 5
- 6
train_prop: 0.7
split: scaffold
dataset: bbbp
epochs: 1000
patience: 35
minimum_epochs: 120
