output_model_dir: ../runs/split/GraphMVP/esol/scaff/train_prop=0.6
input_model_file: ../weights/pretrained/GraphMVP_regression.pth
multiple_seeds:
- 4
- 5
- 6
train_prop: 0.6
split: scaffold
dataset: esol
epochs: 1000
patience: 35
minimum_epochs: 120
