AE_loss: l2
AE_model: AE
CL_neg_samples: 1
CL_similarity_metric: InfoNCE_dot_prod
JK: last
SSL_2D_mode: AM
SSL_masking_ratio: 0
T: 0.1
alpha_1: 1
alpha_2: 1
alpha_3: 0.1
batch_size: 256
beta: 1
config: ../runs/split/GraphMVP/_test/freesolv/random/train_prop=0.8/freesolv_scaff_0_01-05_08-09-41/test_run_multiple_regression.yml
contextpred_neg_samples: 1
csize: 3
cutoff: 10
dataset: freesolv
decay: 0
detach_target: true
device: cuda:1
dropout_ratio: 0.5
emb_dim: 300
epochs: 2
eval_train: true
gamma_joao: 0.1
gamma_joaov2: 0.1
gnn_lr_scale: 1
gnn_type: gin
graph_pooling: mean
input_data_dir: ""
input_model_file: ../weights/pretrained/GraphMVP_regression.pth
lr: 0.001
lr_scale: 1
mask_edge: 0
mask_rate: 0.15
model_3d: schnet
multiple_seeds:
  - 1
noise_level: 0.0
normalize: false
num_filters: 128
num_gaussians: 51
num_interactions: 6
num_layer: 5
num_workers: 0
output_model_dir: ../runs/split/GraphMVP/_test/freesolv/random/train_prop=0.8
readout: mean
runseed: 0
schnet_lr_scale: 1
seed: 42
split: scaffold
train_prop: 0.8
verbose: false
