output_model_dir: ../results/split/GraphMVP/_test/bace/random/train_prop=0.8
input_model_file: ../weights/pretrained/GraphMVP_classification.pth
multiple_seeds:
- 1
- 2
train_prop: 0.8
split: random
dataset: bace
epochs: 2
