output_model_dir: ../results/split/GraphMVP/_test/clintox/scaff/train_prop=0.6
input_model_file: ../weights/pretrained/GraphMVP_classification.pth
multiple_seeds:
- 1
- 2
train_prop: 0.6
split: scaffold
dataset: clintox
epochs: 2
