output_model_dir: ../runs/split/GraphMVP/freesolv/scaff/train_prop=0.6
input_model_file: ../weights/pretrained/GraphMVP_regression.pth
multiple_seeds:
- 1
- 2
- 3
train_prop: 0.6
split: scaffold
dataset: freesolv
epochs: 1000
patience: 35
minimum_epochs: 120
