output_model_dir: ../runs/split/GraphMVP/clintox/random/train_prop=0.7
input_model_file: ../weights/pretrained/GraphMVP_classification.pth
multiple_seeds:
- 4
- 5
- 6
train_prop: 0.7
split: random
dataset: clintox
epochs: 1000
patience: 35
minimum_epochs: 120
