output_model_dir: ../results/split/GraphMVP/_test/tox21_scaff=0.6
input_model_file: ../weights/pretrained/GraphMVP_classification.pth
multiple_seeds:
- 1
- 2
train_prop: 0.6
split: scaffold
dataset: tox21
epochs: 2
