output_model_dir: ../runs/split/GraphCL/hiv/random/train_prop=0.7
input_model_file: ../weights/pretrained/GraphCL_classification.pth
multiple_seeds:
- 1
- 2
- 3
train_prop: 0.7
split: random
dataset: hiv
epochs: 1000
patience: 35
minimum_epochs: 120
